// Unity Build Uber File generated by CMake
// This file is auto generated, do not manually edit it.

#include <StdAfx.h>
#include <C:/Users/Maxwell/Documents/CRYENGINE Projects/WarCompany/Code/Components/Player.cpp>
#include <C:/Users/Maxwell/Documents/CRYENGINE Projects/WarCompany/Code/Components/StdComponent.cpp>

